{
 "title": "Proyecto Capstone",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Monitoreo del motor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltaje",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  Time AS \"time\",\n  distancia\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
      }
     ]
    },
    {
     "title": "Corriente",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 11, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  Time AS \"time\",\n  distancia\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
      }
     ]
    },
    {
     "title": "Corriente",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Time AS \"time\",\n  distancia\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
      }
     ]
    },
    {
     "title": "Voltaje",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Time AS \"time\",\n  distancia\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
      }
     ]
    },
    {
     "title": "Vibraciones",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT\n  Time AS \"time\",\n  distancia\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
      }
     ]
    },
    {
     "title": "Vibraciones",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Time AS \"time\",\n  distancia\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoreo de la planta (Individual)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Distancia",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1s,previous),\n  avg(distancia) AS \"distancia\"\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1s,previous)"
    }
   ]
  },
  {
   "title": "Posición",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1s,previous),\n  avg(posicion) AS \"posicion\"\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1s,previous)"
    }
   ]
  },
  {
   "title": "Distancia",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  distancia\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Posición",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  posicion\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  error\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "U",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  u\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "U",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1s,previous),\n  avg(u) AS \"u\"\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1s,previous)"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1s,previous),\n  avg(error) AS \"error\"\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1s,previous)"
    }
   ]
  },
  {
   "title": "Posición de la base",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  distancia\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Grafica General de todas las variables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gráfica de las variables del sistema",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,1s,previous),\n  avg(distancia) AS \"distancia\",\n  avg(error) AS \"error\",\n  avg(posicion) AS \"posicion\",\n  avg(u) AS \"u\"\nFROM variablesdelproyecto\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1s,previous)"
      }
     ]
    }
   ]
  }
 ]
}